### ISSUE TITLE
repo for resources.robotwebtools.org

### ISSUE THREAD

**Issue by goretkin** [RobotWebTools/robotwebtools.org#61]
Is there a repo for the files under
http://resources.robotwebtools.org/pr2_description/
?

They're not the same as the files under
https://github.com/PR2/pr2_common/tree/indigo-devel/pr2_description

(for example, the ros package pr2_description contains .tif files, whereas the robotwebtools site contains .png files)

Perhaps this information can be added to
http://wiki.ros.org/ros3djs#Mesh_Resource_Hosting

**Comment by jihoonl** [comment]
Perhaps, the materials in http://resources.robotwebtools.org is outdated. I will check it later.

**Comment by goretkin** [comment]
I don't think its outdated. I think it underwent conversion so that the assets could be loaded by THREEjs etc. (the normal maps and color files used to be .tif and were converted to .png).
I'm wondering if there's a place those files live aside from on the CDN.

**Comment by jihoonl** [comment]
Ah, Yes. You are right that resource server serves png files that are converted from tif. And, tif files aren't stored any place in resource server. Do you need tif files for any reason?

**Comment by goretkin** [comment]
Sorry for not being clear. I don't need the .tif files. I was curious if there was a repository there all the rosweb assets (the .pngs, the collada files, the STL files) were stored.

**Comment by jihoonl** [comment]
ok. there is no repository to maintain resources on the server. The resources that are currently served by resource server is manually added.

**Comment by amacneil** [comment]
The resources domain seems to no longer exist
