### ISSUE TITLE
None of the demos working on the website

### ISSUE THREAD

**Issue by TimAdamson21** [RobotWebTools/robotwebtools.org#64]
All four demos found at http://robotwebtools.org/demos.html are not working.

**Comment by DLu** [comment]
It is being worked on. #63 
https://groups.google.com/forum/#!msg/robot-web-tools/PlW1ECoL91Y/uI80cp3zDAAJ

**Comment by jash101** [comment]
Still none of them works for me

**Comment by amacneil** [comment]
The demos are gone now
