### ISSUE TITLE
TypeError: xmlDoc is undefined[详细了解]

### ISSUE THREAD

**Issue by chenguang3312** [RobotWebTools/robotwebtools.org#75]
你好，我在尝试运行demos路径下的/home/mrchen/robotwebtools.github.io/demos/turtlebot-urdf.html页面时．浏览器报错如下：

`TypeError: b is undefined[详细了解] roslib.min.js:2:13904

    d http://static.robotwebtools.org/roslibjs/current/roslib.min.js:2 <anonymous> http://static.robotwebtools.org/ros3djs/current/ros3d.min.js:1 get http://static.robotwebtools.org/roslibjs/current/roslib.min.js:1 callService http://static.robotwebtools.org/roslibjs/current/roslib.min.js:1 e http://static.robotwebtools.org/roslibjs/current/roslib.min.js:1 emit http://static.robotwebtools.org/roslibjs/current/roslib.min.js:1 b http://static.robotwebtools.org/roslibjs/current/roslib.min.js:2 c http://static.robotwebtools.org/roslibjs/current/roslib.min.js:2 onmessage http://static.robotwebtools.org/roslibjs/current/roslib.min.js:2`

请问是否是操作步骤不正确导致的，我使用的是FireFox浏览器，还有请问urdfClient函数ｐａｔｈ参数，如何正确引用本地dae文件，路径如何写

**Comment by amacneil** [comment]
Hello, please report this on the appropriate repo https://github.com/robotWebTools/roslibjs
